name: Auto Scrape M3U Playlist

on:
  workflow_dispatch: # Giữ nút bấm chạy thủ công khi cần
  schedule:
    # Tự động chạy mỗi 2 tiếng 1 lần
    - cron: '0 */2 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cài đặt Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cài đặt thư viện Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium

      - name: Chạy file scraper.py
        run: python scraper.py

      - name: Lưu và Đăng file playlist.m3u lên GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u
          git commit -m "Auto update playlist [skip ci]" || exit 0
          git push
          
